---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Set up Python
        uses: actions/setup-python@v3


      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          echo $HOME/.poetry/bin >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry install -E discord

      - name: "Build & test"
        run: |
          poetry run pytest
          poetry build

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.txt
            *.tar.gz
            *.whl
