# GitHub Action Workflow enforcing our code style and quality.

name: Lint & Tests

# Trigger the workflow on push any branch
on: [push]

# Brand new concurrency setting! This ensures that not more than one run can be triggered for the same commit.
# It is useful for pull requests coming from the main repository since both triggers will match.
concurrency: lint-${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          echo $HOME/.poetry/bin >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry install


      - name: Run pre-commit hooks
        run: |
          poetry run pre-commit

      - name: Run pytest tests
        run: |
          poetry run pytest
